# Generated by Django 5.0.2 on 2024-02-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterU',
            fields=[
                ('EmID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='media/emphoto')),
            ],
        ),
    ]
